mailcow__timezone: Europe/Berlin
mailcow__redirect_http_to_https: yes
#mailcow__theme: darkly
mailcow__config_allow_admin_email_login: y
mailcow__config_skip_clamd: y
mailcow__config_skip_solr: y
mailcow__config_additional_san:
  - imap.*
  - smtp.*
  - mail.n0emis.eu
  - mail.desti.io
  - mail.het.hel.fi.n0emis.eu
  - mail.het.hel.fl.n0emis.eu
  - ganymed.het.hel.fl.n0emis.eu

mailcow__config_http_port: 81
mailcow__config_https_port: 444

borgmatic_before_backup_command:
  - echo "`date` - Starting backup."
  - "cd /opt/mailcow-dockerized && MAILCOW_BACKUP_LOCATION=/root/mailcow-backup ./helper-scripts/backup_and_restore.sh backup all"
borgmatic_after_backup_command:
  - echo "`date` - Finished backup."
  - "rm -r /root/mailcow-backup/*"
