---
- name: reboot
  command: /sbin/reboot

- name: led reload
  command: /etc/init.d/led reload

- name: reload network
  command: /etc/init.d/network reload

- name: restart dnsmasq
  command: /etc/init.d/dnsmasq dnsmasq restart

- name: reload wireless
  command: /sbin/wifi reload

