---
- name: Install required packages
  apt:
    name:
      - strongswan
      - libstrongswan-standard-plugins
      - libcharon-extra-plugins
    state: present

- name: Template ipsec config file
  template:
    src: "ipsec.conf.j2"
    dest: "/etc/ipsec.conf"
  notify: restart strongswan

- name: Template ipsec secrets file
  template:
    src: "ipsec.secrets.j2"
    dest: "/etc/ipsec.secrets"
  notify: restart strongswan

- name: Template strongswan radius config
  template:
    src: "eap-radius.conf.j2"
    dest: "/etc/strongswan.d/charon/eap-radius.conf"
  notify: restart strongswan
