---
#- name: Install dependencies
#  apt:
#    name:
#      - wireguard

# TODO: ...
#- name: Template Network config
#  template:
#    src: interfaces.j2
#    dest: /etc/network/interfaces
#  notify: reload networking

- include_tasks: sysctl.yml
  when: ansible_os_family == "Debian"

- name: test
  debug:
    msg: foo

- name: Install and configure ifupdpwn2
  include_tasks: ifupdown2.yml
  when: "networking_ifupdown2"

- include_tasks: wireguard.yml
  when: "host != inventory_hostname and not networking_ifupdown2 and ansible_os_family == 'Debian'"
  loop: "{{ wireguard_mesh_neighbours }}"
  loop_control:
    loop_var: "host"

- name: Install nftables
  apt:
    name: "nftables"
    state: present
  when: networking_nftables

- name: Copy nftables config
  template:
    src: "{{ networking_nftables_file }}"
    dest: "/etc/nftables.conf"
  notify: reload nftables
  when: networking_nftables

- name: Make sure nftables is enabled and running
  systemd:
    name: "nftables"
    state: started
    enabled: yes
  when: networking_nftables
