---
- name: Install dependencies
  apt:
    name:
      - wireguard

# TODO: ...
#- name: Template Network config
#  template:
#    src: interfaces.j2
#    dest: /etc/network/interfaces
#  notify: reload networking

- include_tasks: wireguard.yml
  when: "hostvars[host].ansible_fqdn != ansible_fqdn"
  loop: "{{ groups['wireguard_member'] }}"
  loop_control:
    loop_var: "host"
