---
borg_encryption_passphrase: "{{ lookup('passwordstore', 'infra/host/{{ ansible_host }}/backup_encryption') }}"
borg_repository: "root@kallisto.int.goe.de.n0emis.eu:/rpool/backup/borg/{{ ansible_host }}"
borg_ssh_command: "ssh -o StrictHostKeyChecking=no"
borgmatic_large_repo: false

borg_source_directories:
  - /home
  - /var
  - /opt
  - /srv
  - /etc
  - /root

borg_exclude_patterns:
  - /var/cache
  - /var/lock
  - /var/spool
  - /var/log
  - /var/lib/docker/image
  - node_modules
  - .venv

borgmatic_cron_hour: "{{ 3 | random(seed=inventory_hostname) }}"
borgmatic_cron_minute: "{{ 59 | random(seed=inventory_hostname) }}"
