---
wireguard_server_address: "10.152.24.1/32"

wireguard_mesh_neighbours:
  - elara.het.nue.de.n0emis.eu
  - himalia.ion.rhr.de.n0emis.eu

networking_ifupdown2: yes
networking_nftables: yes

networking_lo_addr:
  - "172.20.190.125/32"
  - "fdf4:2331:fa09:1::1/128"

borgmatic_cron_hour: "*"
borgmatic_before_backup_command:
  - echo "`date` - Starting backup."
  - "lxc-attach ca-db -- mysqldump --all-databases >> /root/databases.sql"
borgmatic_after_backup_command:
  - echo "`date` - Finished backup."
  - "rm -r /root/databases.sql"

lxc_netmask: "26"
lxc_gateway4: "10.152.24.1"
lxc_gateway6: "fdf4:2331:fa09:1::1"

lxc_containers:
  - name: "ca-db"
    v4: "10.152.24.2"
    v6: "fdf4:2331:fa09:1::2"
  - name: "ca-staging"
    v4: "10.152.24.3"
    v6: "fdf4:2331:fa09:1::3"
  - name: "ca-prod"
    v4: "10.152.24.4"
    v6: "fdf4:2331:fa09:1::4"
  - name: "dn42"
    v4: "10.152.24.5"
    v6: "fdf4:2331:fa09:1::5"

bird_extra: |
  protocol bgp igp_dn42 {
      local as 4200024001;
      neighbor fdf4:2331:fa09:1::5 as 4200024005;

      ipv4 {
          table igp4;
          import filter {
              bgp_local_pref=150;
              accept;
          };
          export filter {
              krt_prefsrc=10.152.24.1;
              accept;
          };
      };
      ipv6 {
          table igp6;
          import filter {
              if net ~ [ fdf4:2331:fa09:1::/64+ ] then {
                  reject;
              }
              bgp_local_pref=150;
              accept;
          };
          export all;
      };
  };
