---
dyndns_host: "pasiphae.int.goe.de"

postgresql_host_users:
  - name: "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_password }}"
postgresql_databases:
  - name: "{{ nextcloud_db }}"
    owner: "{{ nextcloud_db_user }}"

nextcloud_db_type: "pgsql"
nextcloud_db: "nc_kekscloud"
nextcloud_db_user: "nc_kekscloud"
nextcloud_db_password: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu/db') }}"
#nextcloud_directory: "/var/www/kekscloud"

nextcloud_config:
  - key: "instanceid"
    value: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu subkey=user') }}"
  - key: "passwordsalt"
    value: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu subkey=passwordsalt') }}"
  - key: "secret"
    value: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu') }}"
  - key: "dbname"
    value: "{{ nextcloud_db }}"
  - key: "dbuser"
    value: "{{ nextcloud_db_user }}"
  - key: "dbpassword"
    value: "{{ nextcloud_db_password }}"
  - key: "trusted_domains 0"
    value: "pasiphae.int.goe.de.n0emis.eu"
  - key: "trusted_domains 1"
    value: "dev.cloud.n0emis.eu"
  - key: "trusted_domains 2"
    value: "wolke.n0emis.eu"
  - key: "trusted_domains 3"
    value: "wolke.noemis.me"
  - key: "overwriteprotocol"
    value: "https"
  - key: "trusted_proxies 0"
    value: "sinope.int.goe.de.n0emis.eu"
  - key: "memcache.local"
    value: "\\\\OC\\\\Memcache\\\\APCu"
  - key: "memcache.distributed"
    value: "\\\\OC\\\\Memcache\\\\Redis"
  - key: "memcache.locking"
    value: "\\\\OC\\\\Memcache\\\\Redis"
  - key: "redis host"
    value: "localhost"
  - key: "redis port"
    value: "6379"
  - key: "simpleSignUpLink.shown"
    value: "false"
  - key: "ldapIgnoreNamingRules"
    value: "false"
  - key: "ldapProviderFactory"
    value: "OCA\\\\User_LDAP\\\\LDAPProviderFactory"

nextcloud_apps:
  - audioplayer
  - audioplayer_editor
  - bbb
  - calendar
  - contacts
  - cospend
  - deck
  - documentserver_community
  - files_external
  - forms
  - groupfolders
  - impersonate
  - integration_github
  - integration_gitlab
  - integration_mastodon
  - metadata
  - news
  - onlyoffice
  - polls
  - quota_warning
  - sharepoint
  - social
  - socialsharing_email
  - tasks
  - terms_of_service
  - user_ldap
  - user_saml

nextcloud_datadir: "/data"

nginx_vhosts:
  - listen: "81"
    state: "present"
    server_name: "_"
    template: "{{ nginx_vhost_template }}"
    filename: "kekscloud.conf"
    index: "index.php index.html /index.php$request_uri"
    extra_parameters: |
      # set max upload size
      client_max_body_size 512M;
      fastcgi_buffers 64 4K;

      # Enable gzip but do not remove ETag headers
      gzip on;
      gzip_vary on;
      gzip_comp_level 4;
      gzip_min_length 256;
      gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
      gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

      # Pagespeed is not supported by Nextcloud, so if your server is built
      # with the `ngx_pagespeed` module, uncomment this line to disable it.
      #pagespeed off;

      # HTTP response headers borrowed from Nextcloud `.htaccess`
      add_header Referrer-Policy                      "no-referrer"   always;
      add_header X-Content-Type-Options               "nosniff"       always;
      add_header X-Download-Options                   "noopen"        always;
      add_header X-Frame-Options                      "SAMEORIGIN"    always;
      add_header X-Permitted-Cross-Domain-Policies    "none"          always;
      add_header X-Robots-Tag                         "none"          always;
      add_header X-XSS-Protection                     "1; mode=block" always;

      # Remove X-Powered-By, which is an information leak
      fastcgi_hide_header X-Powered-By;

      # Path to the root of your installation
      root /var/www/nextcloud/current;

      # Specify how to handle directories -- specifying `/index.php$request_uri`
      # here as the fallback means that Nginx always exhibits the desired behaviour
      # when a client requests a path that corresponds to a directory that exists
      # on the server. In particular, if that directory contains an index.php file,
      # that file is correctly served; if it doesn't, then the request is passed to
      # the front-end controller. This consistent behaviour means that we don't need
      # to specify custom rules for certain paths (e.g. images and other assets,
      # `/updater`, `/ocm-provider`, `/ocs-provider`), and thus
      # `try_files $uri $uri/ /index.php$request_uri`
      # always provides the desired behaviour.
      index index.php index.html /index.php$request_uri;

      # Default Cache-Control policy
      expires 1m;

      # Rule borrowed from `.htaccess` to handle Microsoft DAV clients
      location = / {
          if ( $http_user_agent ~ ^DavClnt ) {
              return 302 /remote.php/webdav/$is_args$args;
          }
      }

      location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
      }

      # Make a regex exception for `/.well-known` so that clients can still
      # access it despite the existence of the regex rule
      # `location ~ /(\.|autotest|...)` which would otherwise handle requests
      # for `/.well-known`.
      location ^~ /.well-known {
          # The following 6 rules are borrowed from `.htaccess`

          rewrite ^/\.well-known/host-meta\.json  /public.php?service=host-meta-json  last;
          rewrite ^/\.well-known/host-meta        /public.php?service=host-meta       last;
          rewrite ^/\.well-known/webfinger        /public.php?service=webfinger       last;
          rewrite ^/\.well-known/nodeinfo         /public.php?service=nodeinfo        last;

          location = /.well-known/carddav     { return 301 /remote.php/dav/; }
          location = /.well-known/caldav      { return 301 /remote.php/dav/; }

          try_files $uri $uri/ =404;
      }

      # Rules borrowed from `.htaccess` to hide certain paths from clients
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/)  { return 404; }
      location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console)              { return 404; }

      # Ensure this block, which passes PHP files to the PHP process, is above the blocks
      # which handle static assets (as seen below). If this block is not declared first,
      # then Nginx will encounter an infinite rewriting loop when it prepends `/index.php`
      # to the URI, resulting in a HTTP 500 error response.
      location ~ \.php(?:$|/) {
          fastcgi_split_path_info ^(.+?\.php)(/.*)$;
          set $path_info $fastcgi_path_info;

          try_files $fastcgi_script_name =404;

          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $path_info;
          fastcgi_param HTTPS on;

          fastcgi_param modHeadersAvailable true;         # Avoid sending the security headers twice
          fastcgi_param front_controller_active true;     # Enable pretty urls
          fastcgi_pass 127.0.0.1:9000;

          fastcgi_intercept_errors on;
          fastcgi_request_buffering off;
      }

      location ~ \.(?:css|js|svg|gif)$ {
          try_files $uri /index.php$request_uri;
          expires 6M;         # Cache-Control policy borrowed from `.htaccess`
          access_log off;     # Optional: Don't log access to assets
      }

      location ~ \.woff2?$ {
          try_files $uri /index.php$request_uri;
          expires 7d;         # Cache-Control policy borrowed from `.htaccess`
          access_log off;     # Optional: Don't log access to assets
      }

      location / {
          try_files $uri $uri/ /index.php$request_uri;
      }
