---
dyndns_host: "pasiphae.int.goe.de"

postgresql_host_users:
  - name: "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_password }}"
postgresql_databases:
  - name: "{{ nextcloud_db }}"
    owner: "{{ nextcloud_db_user }}"

nextcloud_db_type: "pgsql"
nextcloud_db: "nc_kekscloud"
nextcloud_db_user: "nc_kekscloud"
nextcloud_db_password: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu/db') }}"
#nextcloud_directory: "/var/www/kekscloud"

nextcloud_config:
  - key: "instanceid"
    value: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu subkey=user') }}"
  - key: "passwordsalt"
    value: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu subkey=passwordsalt') }}"
  - key: "secret"
    value: "{{ lookup('passwordstore', 'infra/wolke.n0emis.eu') }}"
  - key: "dbname"
    value: "{{ nextcloud_db }}"
  - key: "dbuser"
    value: "{{ nextcloud_db_user }}"
  - key: "dbpassword"
    value: "{{ nextcloud_db_password }}"
  - key: "trusted_domains 0"
    value: "pasiphae.int.goe.de.n0emis.eu"
  - key: "trusted_domains 1"
    value: "dev.cloud.n0emis.eu"
  - key: "trusted_domains 2"
    value: "wolke.n0emis.eu"
  - key: "trusted_domains 3"
    value: "wolke.noemis.me"
  - key: "overwriteprotocol"
    value: "https"
  - key: "trusted_proxies 0"
    value: "sinope.int.goe.de.n0emis.eu"
  - key: "memcache.local"
    value: "\\\\OC\\\\Memcache\\\\APCu"
  - key: "memcache.distributed"
    value: "\\\\OC\\\\Memcache\\\\Redis"
  - key: "memcache.locking"
    value: "\\\\OC\\\\Memcache\\\\Redis"
  - key: "redis host"
    value: "localhost"
  - key: "redis port"
    value: "6379"
  - key: "simpleSignUpLink.shown"
    value: "false"
  - key: "ldapIgnoreNamingRules"
    value: "false"
  - key: "ldapProviderFactory"
    value: "OCA\\\\User_LDAP\\\\LDAPProviderFactory"
  - key: "default_phone_region"
    value: "de"

nextcloud_apps:
  - audioplayer
  - audioplayer_editor
  - bbb
  - calendar
  - contacts
  - cospend
  - deck
  - documentserver_community
  - files_external
  - forms
  - groupfolders
  - impersonate
  - integration_github
  - integration_gitlab
  - integration_mastodon
  - metadata
  - news
  - onlyoffice
  - polls
  - quota_warning
  - sharepoint
  - social
  - socialsharing_email
  - tasks
  - terms_of_service
  - user_ldap
  - user_saml
  - notify_push

nextcloud_datadir: "/data"
