---
### LOOKING GLASS
bird_lg_webservice_enabled: no
bird_lg_proxy_enabled: yes

### DN42
dn42_wg_private_key: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"

dn42_local_v4: "172.20.190.96"
dn42_local_v6: "fdf4:2331:fa09::1"
dn42_region: "41"

dn42_kernel: false
dn42_collector: true
dn42_configure_linux_network_table: false

dn42_peers:
  - name: "v0tti"
    as: "4242423929"
    v6: "fe80::42:1"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "42001"
      endpoint: "dn42.v0tti.com:1202"
      pubkey: "r8C+hxEcgQ8m5ic20TPbQ4xx5lFYIikouv5yDaNq8AU="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/v0tti') }}"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "margau"
    as: "4242421280"
    v4: "172.22.161.105"
    v6: "fde3:4c0d:2836:ff00::6"
    multiprotocol: yes
    if:
      v6: "fde3:4c0d:2836:ff00::7"
    wg:
      port: "42002"
      endpoint: "wg1.margau.ipv6.church:51823"
      pubkey: "OoGS3vepyVU1tuHSUWJv2jIXJTF7RqOvvQcGC/SJslE="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/margau') }}"
    latency: 2
    bandwidth: 24
    security: 34
  - name: "zotan"
    as: "4242422341"
    v4: "172.20.177.34"  # We are doing multiprotocol
    v6: "fe80::3"
    multiprotocol: yes
    if:
      v4: "172.20.190.96"
      v6: "fe80::42:42:1"
    wg:
      port: "42004"
      endpoint: "nbg1.dn42.zotan.network:42430"
      pubkey: "PlMza8PC6N58vpGqMsBo3UjvjXThl/2WCTK6drjqbgY="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
    state: absent
  - name: "nex"
    as: "4242423012"
    v6: "fd9b:37f7:faf7:3000::2:3:1"
    if:
      v6: "{{ dn42_local_v6 }}"
    multiprotocol: yes
    wg:
      port: "42006"
      endpoint: "dn42-c-2.nexadn.de:51823"
      pubkey: "KwrjRnVR4dyjWFXDlM2Yf9LukYHIfTEvfcMecExuT00="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "mebus"
    as: "4242420112"
    v6: "fdf4:2331:fa09:ff00::2"
    if:
      v6: "fdf4:2331:fa09:ff00::1"
    multiprotocol: yes
    wg:
      port: "42007"
      endpoint: "[2a00:8a60:e019:10de:5054:ff:fed3:70b0]:12612"
      pubkey: "hZv2RTGFAkF3QTHxqwOqwfT8lAGyr7A3J0w+iWwj/S4="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "chrismoos"
    as: "4242421588"
    v4: "172.20.16.141"
    v6: "fe80::1588"
    if:
      v6: "fe80::100"
    multiprotocol: yes
    wg:
      port: "51588"
      endpoint: "de-fra02.dn42.tech9.io:54310"
      pubkey: "MD1EdVe9a0yycUdXCH3A61s3HhlDn17m5d07e4H33S0="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/chrismoos') }}"
    latency: 2
    bandwidth: 24
    security: 34
  - name: "xesxen"
    as: "4242420246"
    v4: "172.20.14.95"
    v6: "fe80::7f61:c133:f5a6"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "42009"
      endpoint: "do-ams3-1.dn42.hackzone.nl:20197"
      pubkey: "eahB0ySIucY6XIsq5mYiyjMDrxlXvH2ffmKIb6WDRFI="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "em0lar"
    as: "4242420215"
    v4: "172.20.209.1"
    v6: "fe80::42:1"
    multiprotocol: yes
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "50215"
      endpoint: "janus.ion.rhr.de.labcode.de:50197"
      pubkey: "VqOQCPVPi5vgVkiyYDN45BnJnZwCwyXfhTjLA16Z+Co="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/em0lar') }}"
    latency: 1
    bandwidth: 24
    security: 34
  - name: "kioubit"
    as: "4242423914"
    v4: "172.20.53.97"
    v6: "fe80::ade0"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "53914"
      endpoint: "de2.g-load.eu:20197"
      pubkey: "B1xSG/XTJRLd+GrWDsB06BqnIq8Xud93YVh/LYYYtUY="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/kioubit') }}"
    latency: 2
    bandwidth: 24
    security: 34
  - name: "e1mo"
    as: "4242420565"
    v4: "172.20.229.160"
    v6: "fe80::43:1"
    multiprotocol: yes
    if:
      v6: "fe80::43:42:1"
    wg:
      port: "50565"
      endpoint: "de-fra1.dn42.net.dont-break.it:20197"
      pubkey: "LjXwHWJXz5koYyVsZ0UjSHr/zpxIUz/dPzucJSFSDUg="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/e1mo') }}"
    latency: 1
    bandwidth: 24
    security: 34
  - name: "clerie"
    as: "4242422574"
    v6: "fe80::42:1"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "52574"
      endpoint: "dn42-il-gw1.net.clerie.de:50197"
      pubkey: "NstPqQwlmmod6yDOMVgoG/r3mwPm0tFVjnbV3doj1Xg="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "uffsalot"
    as: "4242420780"
    v4: "172.20.191.129"
    v6: "fe80::780"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "50780"
      endpoint: "dn42-de-fra4.brand-web.net:40197"
      pubkey: "7V65FxvD9AQetyUr0qSiu+ik8samB4Atrw2ekvC0xQM="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "munsternet"
    as: "4242422237"
    v6: "fe80::42:2237"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "52237"
      endpoint: "de-fra01.dn42.munsternet.eu:20197"
      pubkey: "p8SOiZ+EN6DOHVUbBb/kUiq81Uu006Xrz0B55W+fqDg="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "cperrin"
    as: 4242423735
    v6: "fe80::3735:4"
    multiprotocol: yes
    wg:
      port: "53735"
      endpoint: "de1.dn42.cperrin.xyz:50197"
      pubkey: "JE2oXbqNV2CAJmbmq01VbAYZD11AvvnpENq6mIiLr3A="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "p0tat05"
    as: 4242421876
    v4: "172.22.66.59"
    v6: "fe80::1876"
    multiprotocol: yes
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "51876"
      endpoint: "157.90.166.124:20197"
      pubkey: "rlfzxSL24UfKvl3cZsHcUr+i3MtG13tu8PRdDqOX3A0="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "napshome"
    as: 4242421050
    v4: 172.22.169.141
    v6: fda9:26a9:1c47:1d42:42:42:0197:1050
    multiprotocol: yes
    wg:
      port: "51050"
      endpoint: "ffm1-de.dn42.napshome.net:50197"
      pubkey: "uo7tLeb1QNoRJtecjUV4TeNYgw2imd11oLx7Hftg2SM="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "moecast"
    as: 4242420604
    v4: "172.23.89.3"
    v6: "fe80::604:3"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "50604"
      endpoint: "de1.dn42.cas7.moe:20197"
      pubkey: "1dJpFLegKHKButkXqbv1KLLMTmS6KtFkWBz6GRo2uxE="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "aasg"
    as: 4242420827
    v6: "fe80::2174:c008:1460:d271"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg: 
      port: "50827"
      endpoint: "behemoth.lorkep.trade:50197"
      pubkey: "6oDGG1ssnWdXR9vSeUKsaExw0Ze3005NmLG/Nyb0fEE="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "yura"
    as: 4242422464
    v4: "172.20.191.193"
    v6: "fe80::2464"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "52464"
      endpoint: "fra.dneo.moeternet.com:20197"
      pubkey: "qIhJZf6mTruzO4GTCUrJnLqs9ID4TI1GctRhaRilBkg="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "jlu5"
    as: 4242421080
    v4: "172.20.229.117"
    v6: "fe80::117"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "51080"
      endpoint: "dn42-de-nbg01.jlu5.com:50197"
      pubkey: "oiSSSOMYxiiM0eQP9p8klwEfNn34hkNNv4S289WUciU="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "burble"
    as: 4242422601
    v4: "172.20.129.169"
    v6: "fe80::42:2601:31:1"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "52601"
      endpoint: "dn42-de-fra1.burble.com:20197"
      pubkey: "DQx7LqPiidLHlw0ocBOXQMLg3NFLNT52TyqE1+eTohE="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "sunnet"
    as: 4242423088
    v4: "172.21.100.195"
    v6: "fe80::3088:195"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "53088"
      endpoint: "fra1-de.dn42.6700.cc:20197"
      pubkey: "TWQhJYK+ynNz7A4GMAQSHAyUUKTnAYrBfWTzzjzhAFs="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "lantian"
    as: 4242422547
    v4: "172.22.76.187"
    v6: "fe80::2547"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "52547"
      endpoint: "virtono.lantian.pub:20197"
      pubkey: "DkmSBCIgrxPPZmT07DraoCSD/jSByjPkYqHJWfVZ5hM="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "welterde"
    as: 64738
    v6: fdef:5d0d:ee12:0105:2:fcde:31e5:1
    if:
      v6: fdef:5d0d:ee12:0105:2:fcde:31e5:2
    wg:
      port: "54738"
      endpoint: "gate0.defra0.dn42.welterde.net:42005"
      pubkey: "XC29xTOkt6/Pr7CA0uwRQqQD1Jb2Gof5zkb3HBjlzhs="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "yuetau"
    as: 4242420925
    v4: 172.21.68.37
    v6: fe80::925
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "20925"
      endpoint: "lon.yuetau.net:20197"
      pubkey: "ZGRXw93MgbDloedAxxCssgXjRFQHmk8pHpvCYytToSI="
  - name: "jrb0001_de"
    as: 4242420119
    v4: "172.20.1.2"
    v6: "fe80::119"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "20119"
      endpoint: "[2001:19f0:6c01:176d:5400:1ff:fefe:6698]:20197"
      pubkey: "v5P00HJje1ucENA2VodkKMmrtTlB4fduMvAJLuleo0c="
    blatency: 2
    bbandwidth: 24
    bsecurity: 34
  - name: "jrb0001_fr"
    as: 4242420119
    v4: "172.20.1.4"
    v6: "fe80::119"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "40119"
      endpoint: "[2001:19f0:6801:10ba:5400:2ff:fe0f:b5a7]:20197"
      pubkey: "ol2Coxvh1yrOwoMFHOKpAYnpuv7nLsRjluLK+owJV3U="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "lss233"
    as: 4242421826
    v4: "172.20.143.52"
    v6: "fe80::1826"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "21826"
      endpoint: "lux.n.lss233.com:50197"
      pubkey: "2hVHLTlQtH90qtLOHD9Yx35OpR08o46fcwa7PgeF+Wk="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "c3d2hg"
    as: 64699
    v4: "172.22.99.253"
    v6: "fe80::deca:fbad"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "24699"
      endpoint: "upstream1.dyn.zentralwerk.org:24699"
      pubkey: "1vPtK4jfw2HViW9ZRNaUaUa4Y8OMHu0XroYKmqh/j18="
    latency: 4
    bandwidth: 24
    security: 34
  - name: "moho"
    as: 4242423754
    v4: "169.254.20.1"
    wg:
      port: "23754"
      pubkey: "8aH6TOj3LNKWwqkNaYr2MEW3MvVaUF/526JO6YGNiio="
      endpoint: "dn42.mholtz.de:2020"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "jerryxiao"
    as: "4242423618"
    v4: "172.20.51.120"
    v6: "fe80::3618"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "23618"
      pubkey: "VWxXm7bOTwyHXoVhkQhrGe0LLujl2Oom6XgN8yfGZEE="
      endpoint: "nl.neo.jerryxiao.cc:50105"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "szczot3k"
    as: "4242423124"
    v4: "172.20.149.66"
    v6: "fe80::3124"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "23124"
      pubkey: "7dBbLZa2s7oSsb2gh+umVhz+bs8vv5HPRvilVagl/xc="
      endpoint: "de01.dn42.kszczot.ovh:20005"
    latency: 3
    bandwidth: 24
    security: 34
  - name: "mc36"
    as: "4242421955"
    v4: "172.23.215.195"
    v6: "fd40:cc1e:c0de::1c1"
    if:
      v4: "172.23.215.194"
      v6: "fd40:cc1e:c0de::1c2"
    wg:
      port: 21955
      endpoint: "www.nop.hu:21955"
      pubkey: "5dgl8wj7YvA9fK2m+0ounrnCXQEqhdeg+Trs/mXbFxg="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/mc36') }}"
    latency: 4
    bandwidth: 24
    security: 34
  - name: "kever"
    as: "4242420406"
    v4: "172.20.48.190"
    v6: "fe80::406"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "20406"
      endpoint: "de.kever.us.to:20197"
      pubkey: "Fhs7ut0bFk00xS22oKC6hVfrka0V+ZNA0vUMd5PpeB8="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "periloso"
    as: "4242423770"
    v4: "172.22.118.129"
    v6: "fe80::3770"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "23770"
      endpoint: "rbx1.dn42.servermade.com:50197"
      pubkey: "0ndXPAg17zmVx5CfxMblRfdcDjHRDB6OKBkYvvtq1g0="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "nurex"
    as: "4242423240"
    v4: "172.20.32.146"
    v6: "fe80::3240:2"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "23240"
      endpoint: "rosella.nrx.me:20197"
      pubkey: "6SR8Ss28Edo6hwwGL17ySay3EfK6kPFsm7EcfjUjkXA="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "tchekda"
    as: "4242421722"
    v4: "172.20.4.97"
    v6: "fe80::1722:97"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "21722"
      endpoint: "peer.dn42.tchekda.fr:20197"
      pubkey: "9DX9FeiUcNPrO0ERaVtRslytSNkvOcppeTDo3rfquBQ="
    latency: 3
    bandwidth: 24
    security: 34
  - name: "nicholascw"
    as: "4242421288"
    v4: "172.20.233.136"
    v6: "fe80::1288"
    if:
      v6: "fe80::42:42:1"
    multiprotocol: yes
    wg:
      port: "21288"
      endpoint: "fra1.sc00.org:20197"
      pubkey: "8HApy1uKEe23OIwy2AfT3p2vvKR/bos4ZaAi1ovjBxM="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "ff3l"
    as: "65043"
    v4: "10.119.0.5"
    v6: "fe80::ff31:5"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "30101"
      endpoint: "gw3.ff3l.net:42011"
      pubkey: "+YBiA0JissgSDQe5h1/Auf3MDR/JLEmfR+pmT5dbSxE="
    latency: 2
    bandwidth: 24
    security: 34
  - name: "hexanet" # gone from dn42
    as: "4242423078"
    state: absent
  - name: "wrmsr" # gone from dn42
    state: absent
  - name: "marropax" # gone from dn42
    as: "4242420880"
    state: absent

