---
### LOOKING GLASS
bird_lg_webservice_enabled: no
bird_lg_proxy_enabled: yes

### DN42
dn42_wg_private_key: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"

dn42_local_subnet_v4: "172.20.190.96/27"
dn42_local_subnet_v6: "fdf4:2331:fa09::/48"
dn42_local_subnet_v6_2: "fdf8:7e7f:d097::/48"
dn42_local_v4: "172.20.190.96"
dn42_local_v6: "fdf4:2331:fa09::1"
dn42_local_as: "4242420197"
dn42_region: "41"

dn42_enable_roa: yes

dn42_pingfinder_enable: yes
dn42_pingfinder_uuid: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/pingfinder') }}"

dn42_configure_linux_network_table: yes

dn42_bird2_directory: "/etc/bird/dn42/"
dn42_bird2_template: "templates/dn42/bird.conf.j2"
dn42_bird2_peer_template: "templates/dn42/peer.conf.j2"

dn42_peers:
  - name: "v0tti"
    as: "4242423929"
    v6: "fe80::42:1"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "42001"
      endpoint: "dn42.v0tti.com:1202"
      pubkey: "r8C+hxEcgQ8m5ic20TPbQ4xx5lFYIikouv5yDaNq8AU="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/v0tti') }}"
  - name: "margau"
    as: "4242421280"
    v4: "172.22.161.105"
    v6: "fde3:4c0d:2836:ff00::6"
    multiprotocol: yes
    if:
      v6: "fde3:4c0d:2836:ff00::7"
    wg:
      port: "42002"
      endpoint: "wg1.margau.ipv6.church:51823"
      pubkey: "OoGS3vepyVU1tuHSUWJv2jIXJTF7RqOvvQcGC/SJslE="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/margau') }}"
  - name: "zotan"
    as: "4242422341"
    v4: "172.20.177.34"  # We are doing multiprotocol
    v6: "fe80::3"
    multiprotocol: yes
    if:
      v4: "172.20.190.96"
      v6: "fe80::42:42:1"
    wg:
      port: "42004"
      endpoint: "nbg1.dn42.zotan.network:42430"
      pubkey: "PlMza8PC6N58vpGqMsBo3UjvjXThl/2WCTK6drjqbgY="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
  - name: "hexanet"
    as: "4242423078"
    state: absent
  - name: "nex"
    as: "4242423012"
    v6: "fd9b:37f7:faf7:3000::2:3:1"
    if:
      v6: "{{ dn42_local_v6 }}"
    wg:
      port: "42006"
      endpoint: "dn42-c-2.nexadn.de:51823"
      pubkey: "KwrjRnVR4dyjWFXDlM2Yf9LukYHIfTEvfcMecExuT00="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
  - name: "mebus"
    as: "4242420112"
    v6: "fdf4:2331:fa09:ff00::2"
    if:
      v6: "fdf4:2331:fa09:ff00::1"
    wg:
      port: "42007"
      endpoint: "[2a00:8a60:e019:10de:5054:ff:fed3:70b0]:12612"
      pubkey: "hZv2RTGFAkF3QTHxqwOqwfT8lAGyr7A3J0w+iWwj/S4="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
  - name: "chrismoos"
    as: "4242421588"
    v4: "172.20.16.141"
    v6: "fe80::1588"
    if:
      v6: "fe80::100"
    wg:
      port: "42008"
      endpoint: "de-fra02.dn42.tech9.io:54310"
      pubkey: "MD1EdVe9a0yycUdXCH3A61s3HhlDn17m5d07e4H33S0="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/chrismoos') }}"
  - name: "xesxen"
    as: "4242420246"
    v4: "172.20.14.95"
    v6: "fe80::7f61:c133:f5a6"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "42009"
      endpoint: "do-ams3-1.dn42.hackzone.nl:20197"
      pubkey: "eahB0ySIucY6XIsq5mYiyjMDrxlXvH2ffmKIb6WDRFI="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
  - name: "wrmsr"
    state: absent
  - name: "marropax"
    as: "4242420880"
    state: absent
  - name: "em0lar"
    as: "4242420215"
    v4: "172.20.209.1"
    v6: "fe80::42:1"
    multiprotocol: yes
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "50215"
      endpoint: "janus.ion.rhr.de.labcode.de:50197"
      pubkey: "VqOQCPVPi5vgVkiyYDN45BnJnZwCwyXfhTjLA16Z+Co="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/em0lar') }}"
  - name: "kioubit"
    as: "4242423914"
    v4: "172.20.53.97"
    v6: "fe80::ade0"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "53914"
      endpoint: "de2.g-load.eu:20197"
      pubkey: "B1xSG/XTJRLd+GrWDsB06BqnIq8Xud93YVh/LYYYtUY="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/kioubit') }}"
  - name: "e1mo"
    as: "4242420565"
    v4: "172.20.229.160"
    v6: "fe80::43:1"
    multiprotocol: yes
    if:
      v6: "fe80::43:42:1"
    wg:
      port: "50565"
      endpoint: "de-fra1.dn42.net.dont-break.it:20197"
      pubkey: "LjXwHWJXz5koYyVsZ0UjSHr/zpxIUz/dPzucJSFSDUg="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/e1mo') }}"
  - name: "clerie"
    as: "4242422574"
    v6: "fe80::42:1"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "52574"
      endpoint: "dn42-il-gw1.net.clerie.de:50197"
      pubkey: "NstPqQwlmmod6yDOMVgoG/r3mwPm0tFVjnbV3doj1Xg="
      privkey: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/dn42/default') }}"
  - name: "uffsalot"
    as: "4242420780"
    v4: "172.20.191.129"
    v6: "fe80::780"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "50780"
      endpoint: "dn42-de-fra4.brand-web.net:40197"
      pubkey: "7V65FxvD9AQetyUr0qSiu+ik8samB4Atrw2ekvC0xQM="
  - name: "munsternet"
    as: "4242422237"
    v6: "fe80::42:2237"
    if:
      v6: "fe80::42:42:1"
    wg:
      port: "52237"
      endpoint: "de-fra01.dn42.munsternet.eu:20197"
      pubkey: "p8SOiZ+EN6DOHVUbBb/kUiq81Uu006Xrz0B55W+fqDg="

