---
- name: configure openwrt accesspoints
  hosts: openwrt !cr
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: 'opkg update && opkg install python3-light && opkg install python3-logging && opkg install python3-distutils'
  roles:
    - accespoint

