---
- name: configure openwrt accesspoints
  hosts: openwrt !cr
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: 'opkg update && opkg install python3-light'

  tasks:
    - name: add user to root's authorized_keys
      authorized_key:
        user: root
        key: "{{ item.public_key }}"
        path: /etc/dropbear/authorized_keys
        state: present
      with_items:
      - "{{ users }}"
      when: item.state != 'absent' and item.public_key is defined and item.sudo is defined and item.sudo

    - name: remove user from root's authorized_keys
      authorized_key:
        user: root
        key: "{{ item.public_key }}"
        path: /etc/dropbear/authorized_keys
        state: absent
      with_items:
      - "{{ users }}"
      when: item.state == 'absent' and item.public_key is defined

    - name: remove packages
      opkg:
        name: wpad-mini luci luci-app-firewall luci-mod-admin-full luci-proto-ipv6 luci-proto-ppp luci-theme-bootstrap luci-base luci-lib-jsonc luci-lib-nixio luci-lib-ip
        state: absent

    - name: install wpad
      opkg:
        name: wpad
        state: present
        update_cache: yes

- hosts: wndr
  gather_facts: no
  tasks:
    - name: disable status leds
      shell: 'for i in /sys/class/leds/* ; do echo 0 > "$i"/brightness; done'
      args:
        executable: /bin/ash

    - name: disable switch leds
      shell: 'for i in 0 1 2 3 4; do swconfig dev switch0 port $i set led 0; done'
      args:
        executable: /bin/ash

    - name: disable status leds permanently
      lineinfile:
        path: /etc/rc.local
        line: 'for i in /sys/class/leds/* ; do echo 0 > "$i"/brightness; done'
        insertbefore: exit 0

    - name: disable switch leds permanently
      lineinfile:
        path: /etc/rc.local
        line: 'for i in 0 1 2 3 4; do swconfig dev switch0 port $i set led 0; done'
        insertbefore: exit 0

- hosts: wndr
  roles:
    - openwrt
  vars:
    openwrt_install_recommended_packages: no
  tasks:
    - name: disable autostarting leds
      uci:
        command: section
        config: system
        type: led
        key: "system.{{ item.key }}"
        value:
          name: "{{ item.name }}"
          sysfs: "{{ item.sysfs }}"
          trigger: 'none'
          brightness: 0
          default: 0
      with_items:
        - name: USB LED (green)
          key: led_usb
          sysfs: 'netgear:green:usb'
        - name: power LED (green)
          key: led_power
          sysfs: 'netgear:green:power'
        - name: WAN LED (green)
          key: led_wan
          sysfs: 'netgear:green:wan'
        - name: 2.4GHz LED (yellow)
          key: led_24g
          sysfs: 'ath9k-phy0'
        - name: 5GHz LED (blue)
          key: led_5g
          sysfs: 'ath9k-phy1'

    - name: commit changes
      uci:
        command: commit
      notify: led reload

  handlers:
    - name: led reload
      service:
        name: led
        state: reloaded
