---
- name: Install requirements
  apt:
    name:
      - gpg
      - tcpdump
      - mtr
  when: ansible_os_family == "Debian"

- name: Add birds packaging Key 1/2
  apt_key:
    url: "https://bird.network.cz/debian/apt.key"
    state: present
  when: ansible_distribution == "Debian"

- name: Add birds packaging Key 2/2
  apt_key:
    url: "https://packages.sury.org/bird/apt.gpg"
    state: present
  when: ansible_distribution == "Debian"

- name: Ensure bird repos are present
  apt_repository:
    repo: "deb https://bird.network.cz/debian/ {{ ansible_distribution_release }} main"
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Install bird2
  apt:
    deb: "https://build.n0emis.eu/repositories/bird2.deb"
    state: present
  when: ansible_fqdn == "himalia.ion.rhr.de.n0emis.eu"

- name: Install bird2
  apt:
    name: "bird2"
    state: present
  when: ansible_fqdn != "himalia.ion.rhr.de.n0emis.eu" and ansible_os_family == "Debian"

- name: Copy bird config-file
  template:
    dest: "{{ bird_config_file }}"
    src: "bird.conf.j2"
  notify: reload bird

- name: Ensure bird service is enabled and started
  systemd:
    name: "bird.service"
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"
