---
- block:
  - name: Install requirements
    apt:
      name:
        - gpg
        - tcpdump
        - mtr

  - name: Ensure forwarding of ipv4-packets is allowed
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present

  - name: Ensure forwarding of ipv6-packets is allowed
    sysctl:
      name: net.ipv6.conf.all.forwarding
      value: '1'
      state: present

  - name: Ensure reverse path filtering is disabled for v4
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '0'
      state: present

  - name: Ensure default reverse path filtering is disabled for v4
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '0'
      state: present

  - name: Ensure no redirects are sent for v4
    sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: '0'
      state: present

  - name: Ensure no redirects are accepted for v4
    sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: '0'
      state: present
  when: ansible_os_family == "Debian"

- name: Add birds packaging Key
  apt_key:
    url: "https://bird.network.cz/debian/apt.key"
    state: present
  when: ansible_distribution == "Debian"

- name: Ensure bird repos are present
  apt_repository:
    repo: "deb https://bird.network.cz/debian/ {{ ansible_distribution_release }} main"
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: Install bird2
  apt:
    deb: "https://build.n0emis.eu/repositories/bird2.deb"
    state: present
  when: ansible_distribution == "Debian"


- name: Install bird2
  apt:
    name: "bird2"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Copy bird config-file
  template:
    dest: "{{ bird_config_file }}"
    src: "bird.conf.j2"
  notify: reload bird

- name: Ensure bird service is enabled and started
  systemd:
    name: "bird.service"
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"
