http:
  routers:
    service-netbox-http:
      rule: "Host(`netbox.n0emis.eu`) || Host(`netbox.noemis.me`)"
      service: "service-netbox@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    service-netbox-https:
      rule: "Host(`netbox.n0emis.eu`) || Host(`netbox.noemis.me`)"
      service: "service-netbox@file"
      entryPoints:
        - "https"
      middlewares:
        - "removeAuthHeaders"
      tls:
        certResolver: "le_http"
  services:
    service-netbox:
      loadBalancer:
        servers:
          - url: "http://{{ louketo_netbox_listen }}"
  middlewares:
    removeAuthHeaders:
      headers:
        customRequestHeaders:
          X-Auth-Email: ""
          X-Auth-Audience: ""
          X-Auth-ExpiresIn: ""
          X-Auth-Groups: ""
          X-Auth-Roles: ""
          X-Auth-Subject: ""
          X-Auth-Token: ""
          X-Auth-UserID: ""
          X-Auth-Username: ""
