http:
  routers:
    service-keycloak-http:
      rule: "Host(`auth.n0emis.eu`) || Host(`auth.noemis.me`) || Host(`keycloak.n0emis.eu`) || Host(`keycloak.noemis.me`)"
      service: "service-keycloak@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    service-keycloak-https:
      rule: "Host(`auth.n0emis.eu`) || Host(`auth.noemis.me`) || Host(`keycloak.n0emis.eu`) || Host(`keycloak.noemis.me`)"
      service: "service-keycloak@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
  services:
    service-keycloak:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ keycloak_http_port }}"
