http:
  routers:
    service-keycloak-http:
      rule: "Host(`auth.n0emis.eu`) || Host(`auth.noemis.me`) || Host(`ipa.noemis.me`)"
      service: "service-keycloak@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    service-keycloak-https:
      rule: "Host(`auth.n0emis.eu`) || Host(`auth.noemis.me`) || Host(`ipa.noemis.me`)"
      service: "service-keycloak@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "{{ traefik_default_cert_resovler }}"
        domains:
          - main: "auth.n0emis.eu"
            sans:
              - "ipa.noemis.me"
              - "auth.noemis.me"
    service-keycloak-metrics-https:
      rule: "(Host(`auth.n0emis.eu`) || Host(`auth.noemis.me`)) && (Path(`/health`))"
      service: "service-keycloak-metrics@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "{{ traefik_default_cert_resovler }}"
        domains:
          - main: "auth.n0emis.eu"
            sans:
              - "ipa.noemis.me"
              - "auth.noemis.me"
  services:
    service-keycloak:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ keycloak_http_port }}"
    service-keycloak-metrics:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ keycloak_management_http_port }}"
